CREATE TABLE "characters" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"name" varchar(100) NOT NULL,
	"species" varchar(50) NOT NULL,
	"background" varchar(50) NOT NULL,
	"alignment" varchar(30),
	"experience_points" integer DEFAULT 0 NOT NULL,
	"classes" jsonb NOT NULL,
	"strength" integer NOT NULL,
	"dexterity" integer NOT NULL,
	"constitution" integer NOT NULL,
	"intelligence" integer NOT NULL,
	"wisdom" integer NOT NULL,
	"charisma" integer NOT NULL,
	"saving_throw_proficiencies" jsonb NOT NULL,
	"skill_proficiencies" jsonb NOT NULL,
	"armor_class" integer NOT NULL,
	"speed" integer NOT NULL,
	"hit_points_max" integer NOT NULL,
	"hit_points_current" integer NOT NULL,
	"hit_points_temp" integer DEFAULT 0 NOT NULL,
	"death_save_successes" integer DEFAULT 0 NOT NULL,
	"death_save_failures" integer DEFAULT 0 NOT NULL,
	"heroic_inspiration" boolean DEFAULT false NOT NULL,
	"proficiencies" jsonb NOT NULL,
	"weapon_masteries" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"attacks" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"spell_slots" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"spells_known" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"inventory" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"currency" jsonb NOT NULL,
	"features" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"personality" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "characters" ADD CONSTRAINT "characters_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;