import type { Character } from 'shared';

// Персонаж со всеми видами полей — для тестов формы и страниц персонажей.
export const sampleCharacter: Character = {
  id: '11111111-1111-4111-8111-111111111111',
  userId: 'user-1',
  name: 'Арагорн',
  species: 'Человек',
  background: 'Солдат',
  alignment: null,
  experiencePoints: 900,
  classes: [
    { class: 'Следопыт', level: 3, subclass: 'Охотник' },
    { class: 'Воин', level: 1 },
  ],
  proficiencyBonus: 2,
  abilityScores: {
    strength: 15,
    dexterity: 14,
    constitution: 13,
    intelligence: 10,
    wisdom: 12,
    charisma: 8,
  },
  savingThrowProficiencies: ['strength', 'dexterity'],
  skillProficiencies: [
    { skill: 'survival', expertise: true },
    { skill: 'athletics', expertise: false },
  ],
  armorClass: 15,
  speed: 30,
  hitPointsMax: 28,
  hitPointsCurrent: 20,
  hitPointsTemp: 5,
  deathSaveSuccesses: 1,
  deathSaveFailures: 0,
  heroicInspiration: true,
  proficiencies: {
    armor: ['Лёгкие'],
    weapons: ['Простое'],
    tools: [],
    languages: ['Общий', 'Эльфийский'],
  },
  weaponMasteries: ['Длинный меч'],
  attacks: [],
  spellSlots: {},
  spellsKnown: [],
  inventory: [{ name: 'Верёвка', quantity: 1 }],
  currency: { cp: 1, sp: 2, ep: 0, gp: 30, pp: 0 },
  features: [],
  personality: { traits: 'Молчалив', backstory: 'Долгая история' },
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-02T00:00:00.000Z',
};
